variables:
 #older versions of git have issues fetching. 
 GIT_STRATEGY: clone

before_script:
  - docker info
  - '[ -d tmp ] || mkdir tmp'
  - git clone https://github.com/OSC/ondemand-packaging.git tmp/ondemand-packaging
  - cp /systems/osc_certs/gpg/ondemand/.gpgpass $CI_PROJECT_DIR/tmp/ondemand-packaging/
  - cp /systems/osc_certs/gpg/ondemand/ondemand.sec $CI_PROJECT_DIR/tmp/ondemand-packaging/
stages:
  - build
  - deploy

rpm-build:
  variables:
    BUILD_SH: "./tmp/ondemand-packaging/build.sh"
    WORK_DIR: "$CI_PROJECT_DIR/tmp/work"
    OUTPUT_DIR: "$CI_PROJECT_DIR/tmp/output"
    PKGING_DIR: "$CI_PROJECT_DIR/packaging"
  stage: build
  only:
    - tags
  script:
    - $BUILD_SH -w $WORK_DIR -o $OUTPUT_DIR -V $CI_COMMIT_TAG -u -v $PKGING_DIR
  artifacts:
    paths:
      - tmp/output
    name: "$CI_PROJECT_NAME-$CI_COMMIT_TAG"


rpm-deploy:
  variables:
    RLS_SCRIPT: "./tmp/ondemand-packaging/release.py"
    RLS_KEY: "/systems/osc_certs/ssh/ondemand-packaging/id_rsa"
    RLS_OUTPUT: "./tmp/output/*"
    SECTION: "main"
  stage: deploy
  only:
    - tags
  script:
    - if [[ "$CI_COMMIT_TAG" =~ .*_.* ]]; then export SECTION=ci; fi
    - $RLS_SCRIPT --debug --pkey $RLS_KEY -c $SECTION $RLS_OUTPUT
