name: test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Setup Ruby using Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0.2"
          bundler-cache: true
          bundler: "2.2.22"

      - name: Install gems
        run: bundle install

      - name: Test
        run: bundle exec rake test
